import type { LoanRequest, DashboardStats, TimeSeriesData, RiskDistribution, AuditLog, Notification } from '@/types'

export const mockStats: DashboardStats = {
  totalRequests: 1250,
  totalRequestsChange: 12.5,
  approved: 850,
  approvedChange: 10.2,
  pending: 250,
  pendingChange: 5.4,
  rejected: 150,
  rejectedChange: -2.1,
}

export const mockTimeSeries: TimeSeriesData[] = [
  { month: 'Jan', requests: 180, approved: 120, rejected: 20 },
  { month: 'Feb', requests: 220, approved: 160, rejected: 25 },
  { month: 'Mar', requests: 195, approved: 140, rejected: 18 },
  { month: 'Apr', requests: 240, approved: 180, rejected: 30 },
  { month: 'May', requests: 280, approved: 210, rejected: 28 },
  { month: 'Jun', requests: 310, approved: 240, rejected: 35 },
  { month: 'Jul', requests: 350, approved: 270, rejected: 40 },
]

export const mockRiskDistribution: RiskDistribution = {
  low: 60,
  medium: 30,
  high: 10,
}

export const mockRequests: LoanRequest[] = [
  {
    id: '#1001',
    applicant: 'Ahmed Ali',
    amount: 25000,
    status: 'APPROVED',
    risk: 'LOW',
    createdAt: '2024-06-01',
    updatedAt: '2024-06-02',
    purpose: 'Business expansion',
    term: 24,
  },
  {
    id: '#1002',
    applicant: 'Sara Mohamed',
    amount: 15000,
    status: 'PENDING',
    risk: 'MEDIUM',
    createdAt: '2024-06-02',
    updatedAt: '2024-06-02',
    purpose: 'Equipment purchase',
    term: 12,
  },
  {
    id: '#1003',
    applicant: 'Omar Hassan',
    amount: 40000,
    status: 'IN_REVIEW',
    risk: 'HIGH',
    createdAt: '2024-06-02',
    updatedAt: '2024-06-03',
    purpose: 'Real estate',
    term: 60,
  },
  {
    id: '#1004',
    applicant: 'Nour Ahmed',
    amount: 10000,
    status: 'REJECTED',
    risk: 'HIGH',
    createdAt: '2024-06-03',
    updatedAt: '2024-06-04',
    purpose: 'Personal loan',
    term: 6,
  },
  {
    id: '#1005',
    applicant: 'Kareem Sayed',
    amount: 32000,
    status: 'VALIDATED',
    risk: 'LOW',
    createdAt: '2024-06-04',
    updatedAt: '2024-06-04',
    purpose: 'Vehicle financing',
    term: 36,
  },
  {
    id: '#1006',
    applicant: 'Laila Ibrahim',
    amount: 18000,
    status: 'RISK_ASSESSED',
    risk: 'MEDIUM',
    createdAt: '2024-06-04',
    updatedAt: '2024-06-05',
    purpose: 'Home renovation',
    term: 24,
  },
  {
    id: '#1007',
    applicant: 'Mostafa Kamal',
    amount: 55000,
    status: 'INITIATED',
    risk: 'HIGH',
    createdAt: '2024-06-05',
    updatedAt: '2024-06-05',
    purpose: 'Business startup',
    term: 48,
  },
  {
    id: '#1008',
    applicant: 'Hana Farouk',
    amount: 8000,
    status: 'APPROVED',
    risk: 'LOW',
    createdAt: '2024-06-05',
    updatedAt: '2024-06-06',
    purpose: 'Education loan',
    term: 12,
  },
]

export const mockAuditLogs: AuditLog[] = [
  {
    id: '1',
    userId: 'u1',
    userName: 'John Doe',
    action: 'APPROVED',
    resource: 'LoanRequest',
    resourceId: '#1001',
    details: 'Approved loan request for Ahmed Ali',
    ipAddress: '192.168.1.1',
    createdAt: '2024-06-02T10:30:00Z',
  },
  {
    id: '2',
    userId: 'u2',
    userName: 'Jane Smith',
    action: 'CREATED',
    resource: 'LoanRequest',
    resourceId: '#1002',
    details: 'Created new loan request',
    ipAddress: '192.168.1.2',
    createdAt: '2024-06-02T09:15:00Z',
  },
  {
    id: '3',
    userId: 'u1',
    userName: 'John Doe',
    action: 'REJECTED',
    resource: 'LoanRequest',
    resourceId: '#1004',
    details: 'Rejected loan request - high risk profile',
    ipAddress: '192.168.1.1',
    createdAt: '2024-06-04T14:00:00Z',
  },
]

export const mockNotifications: Notification[] = [
  {
    id: '1',
    title: 'New Loan Request',
    message: 'Ahmed Ali submitted a new loan request for $25,000',
    type: 'info',
    read: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 5).toISOString(),
  },
  {
    id: '2',
    title: 'Request Approved',
    message: 'Request #1001 has been approved successfully',
    type: 'success',
    read: false,
    createdAt: new Date(Date.now() - 1000 * 60 * 30).toISOString(),
  },
  {
    id: '3',
    title: 'High Risk Alert',
    message: 'Request #1003 flagged as HIGH risk',
    type: 'warning',
    read: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
  },
  {
    id: '4',
    title: 'Request Rejected',
    message: 'Request #1004 was rejected due to high risk profile',
    type: 'error',
    read: true,
    createdAt: new Date(Date.now() - 1000 * 60 * 60 * 5).toISOString(),
  },
]
